name: hsi
channels:
  - pytorch
  - default
  - conda-forge
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - jupyter
  - matplotlib
  - opencv
  - scikit-learn
  - scikit-image
  - torchmetrics
  - pip
  - pip:
    - -r requirements.txt