num_tasks: 31
smoke: 0
data_path: "./datasets/data/CAVE"
num_epochs: 200
save_path: "artifacts/dssp_best_3.pt"
num_hidden_dgp_dims: 16
num_inducing: 256
batch_size: 4096
num_batches_to_train: 500
gpu_idx: 0