experiment:
  name: 'exp 1'

device: 1

model:
 name: 'ca_siamese'
 args: [6, 3, 256, 4]

dataset:
  type: jasper_ridge
  kwargs:
    single_img_path: 'data/jasper/jasper_ridge_224.mat'
    single_gt_path: 'data/jasper/jasper_ridge_gt.mat'
    start_band: 380
    end_band: 2500
    rgb_width: 64 
    rgb_height: 64
    hsi_width: 32 
    hsi_height: 32
    channels: [20, 60, 80, 100, 120, 140]
  batch_size: 16