experiment:
  name: 'exp 1'

device: 1
num_epochs: 40

model:
 name: 'cnn'
 kwargs:
  hsi_in: 6
  msi_in: 3
  latent_dim: 256
  output_channels: 4

dataset:
  name: jasper_ridge
  kwargs:
    classes: ["road", "soil", "water", "tree"]
    single_img_path: 'data/jasper/jasper_ridge_224.mat'
    single_gt_path: 'data/jasper/jasper_ridge_gt.mat'
    start_band: 380
    end_band: 2500
    rgb_width: 16
    rgb_height: 16
    hsi_width: 8 
    hsi_height: 8
    channels: [20, 60, 80, 100, 120, 140]
  batch_size: 2048

loss: 
  name: focal
  kwargs:
    gamma: 3.0
