experiment:
  name: 'exp 1'

device: 1
num_epochs: 40

model:
 name: pixel_mlp
 kwargs:
  hsi_in: 12
  msi_in: 3
  latent_dim: 256
  output_channels: 4
  embedding_dim: 256
  pe: 'fourier'
  act: 'snake'
  a: 1.0

dataset:
  name: jasper_ridge_pixel
  kwargs:
    classes: ["road", "soil", "water", "tree"]
    single_img_path: 'data/jasper/jasper_ridge_224.mat'
    single_gt_path: 'data/jasper/jasper_ridge_gt.mat'
    start_band: 380
    end_band: 2500
    rgb_width: 16
    rgb_height: 16
    hsi_width: 8 
    hsi_height: 8
    top_k: 12
    channels:
    gamma: 0.4
    contrast_enhance: True
    conductivity: 0.6341031137853861
    window_size: 3
    A: 0.8
    split_ratio: 0.5
  batch_size: 2048

loss: 
  name: focal
  kwargs:
    gamma: 3.0
