experiment:
  name: 'exp 2'

device: 0
num_epochs: 40

model:
 name: 'ca_siamese'
 kwargs:
  hsi_in: 162  
  msi_in: 3
  latent_dim: 256
  output_channels: 6
  embedding:
    name: "fourier"
    scale: 2.0

dataset:
  name: urban
  kwargs:
    data_dir: '/mnt/data/shubham/hsi_msi/urban'
    rgb_width: 64
    rgb_height: 64
    hsi_width: 32 
    hsi_height: 32
    gamma: 0.4
    contrast_enhance: True
    conductivity: 0.9406637619554582
    window_size: 5
    channels:
    top_k: 6
    A: 0.8
    
  batch_size: 512

loss: 
  name: focal
  kwargs:
    gamma: 3.0