experiment:
  name: 'exp 2'

device: 1
num_epochs: 40

model:
 name: 'pixel_mlp'
 kwargs:
  hsi_in: 24 
  msi_in: 3
  latent_dim: 256
  output_channels: 6
  feature_embedding_dim: 128
  position_embedding_dim: 256
  fe_alg: None
  pe_alg: sinusoidal
  act: 'snake'
  a: 1.0
  input_mode: hsi_msi
  use_pe: False

dataset:
  name: urban
  kwargs:
    data_dir: '/mnt/data/shubham/hsi_msi/urban'
    rgb_width: 64
    rgb_height: 64
    hsi_width: 32 
    hsi_height: 32
    gamma: 0.4
    contrast_enhance: True
    conductivity: 0.9406637619554582
    window_size: 5
    channels:
    top_k: 24
    A: 0.8
    split_ratio: 0.8
    data_type: pixel
    low_light: True
    
    
  batch_size: 256 # 512

loss: 
  name: focal
  kwargs:
    gamma: 3.0